version: '3.7'

services:
  iceesui:
    container_name: iceesui
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 11633:11633
    environment:
      - CHOKIDAR_USEPOLLING=true

    stdin_open: true