version: '3.7'

services:
  iceesui:
    container_name: iceesui
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 4567:4567
    environment:
      - CHOKIDAR_USEPOLLING=true

    stdin_open: true